openapi: "3.0.1"
info:
  title: "Message Plugin"
  description: "Plugin for sending messages, executing commands, and retrieving pending messages via ChatGPT."
  version: "v1"
servers:
  - url: "http://localhost:5003"
paths:
  /ai-plugin.json:
    get:
      operationId: "getAIPluginConfig"
      summary: "Get AI plugin config"
      description: "Returns the AI plugin configuration."
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                additionalProperties:
                  type: "string"
        default:
          description: "Unexpected error"
  /openapi.yaml:
    get:
      operationId: "getOpenAPISpec"
      summary: "Get OpenAPI spec"
      description: "Returns the OpenAPI specification."
      responses:
        "200":
          description: "OK"
          content:
            text/yaml:
              schema:
                type: "string"
        default:
          description: "Unexpected error"
  /send-message:
    post:
      operationId: "sendMessage"
      summary: "Send a message"
      description: "Accepts any message in JSON or XML format."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties: {}
              additionalProperties: true
          application/xml:
            schema:
              type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sendMessageResponse"
        default:
          description: "Unexpected error"
  /get-messages:
    post:
      operationId: "getMessages"
      summary: "Get pending messages"
      description: "Returns pending messages. Filter by including a JSON object in the request body."
      description: "Returns pending messages. Filter by including a JSON object in the request body."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties: {}
              additionalProperties:
                type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties: {}
                  additionalProperties:
                    type: "string"
        default:
          description: "Unexpected error"
components:
  schemas:
    sendMessageResponse:
      type: "object"
      properties:
        status:
          type: "string"
          description: "Status of the message send operation."
