openapi: "3.0.1"
info:
  title: "Message Plugin"
  description: "Plugin for sending messages via ChatGPT."
  version: "v1"
servers:
  - url: "https://katydid-glorious-slightly.ngrok-free.app/"
paths:
  /ai-plugin.json:
    get:
      operationId: "getAIPluginConfig"
      summary: "Get AI chatgpt_plugin config"
      description: "Returns the AI chatgpt_plugin configuration."
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                properties:  # Define the expected properties here
                  pluginName:
                    type: "string"
                    description: "The name of the plugin."
                  version:
                    type: "string"
                    description: "The version of the plugin."
                  author:
                    type: "string"
                    description: "The author of the plugin."
                  # Add other properties as needed
                # If you have additional, undefined properties, you can keep this line:
                additionalProperties: false  # Set to false if all properties are defined
  /openapi.yaml:
    get:
      operationId: "getOpenAPISpec"
      summary: "Get OpenAPI spec"
      description: "Returns the OpenAPI specification."
      responses:
        "200":
          description: "OK"
          content:
            text/yaml:
              schema:
                type: "string"
        default:
          description: "Unexpected error"
  /send-message:
    post:
      operationId: "sendMessage"
      summary: "Send a message"
      description: "Accepts any message in JSON format."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message_type:
                  type: string
                content:
                  type: string
              required:
                - message_type
                - content

      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sendMessageResponse"
        default:
          description: "Unexpected error"
components:
  schemas:
    sendMessageResponse:
      type: "object"
      properties:
        status:
          type: "string"
          description: "Status of the message send operation."
