openapi: "3.0.1"
info:
  title: "Message Plugin"
  description: "Plugin for sending messages, executing commands, and retrieving pending messages via ChatGPT."
  version: "v1"
servers:
  - url: "http://localhost:5003"
paths:
  /ai-plugin.json:
    get:
      operationId: "getAIPluginConfig"
      summary: "Get AI chatgpt_plugin config"
      description: "Returns the AI chatgpt_plugin configuration."
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "object"
                additionalProperties:
                  type: "string"
        default:
          description: "Unexpected error"
  /openapi.yaml:
    get:
      operationId: "getOpenAPISpec"
      summary: "Get OpenAPI spec"
      description: "Returns the OpenAPI specification."
      responses:
        "200":
          description: "OK"
          content:
            text/yaml:
              schema:
                type: "string"
        default:
          description: "Unexpected error"
  /send-message:
    post:
      operationId: "sendMessage"
      summary: "Send a message"
      description: "Accepts any message in JSON format."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                sender_actor:
                  type: "string"
                sender_agent:
                  type: "string"
                log_correlation_path:
                  type: "string"
                recipient_agent:
                  type: "string"
                recipient_actor:
                  type: "string"
                message_type:
                  type: "string"
                subject:
                  type: "string"
                content:
                  type: "string"
              required:
                - sender_actor
                - sender_agent
                - log_correlation_path
                - recipient_agent
                - recipient_actor
                - message_type
                - subject
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/sendMessageResponse"
        default:
          description: "Unexpected error"
  /get-messages:
    post:
      operationId: "getMessages"
      summary: "Get pending messages"
      description: "Returns pending messages. Filter by including a JSON object in the request body."
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties: {}
              additionalProperties:
                type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "array"
                items:
                  type: "object"
                  properties: {}
                  additionalProperties:
                    type: "string"
        default:
          description: "Unexpected error"
components:
  schemas:
    sendMessageResponse:
      type: "object"
      properties:
        status:
          type: "string"
          description: "Status of the message send operation."
